In [1]:
l = [234, 345, 456, 567, 678]

In [2]:
l

[234, 345, 456, 567, 678]

In [22]:
l[2:]

[456, 567]

In [23]:
d = l[2:]

In [24]:
d

[456, 567]

In [ ]:
d[:] = 222

In [25]:
d

[456, 567]

In [3]:
import numpy as np

In [4]:
a = np.array(l)

In [5]:
a

array([234, 345, 456, 567, 678])

In [6]:
b = np.array([2, 'shreyas', 3.5])

In [7]:
b

array(['2', 'shreyas', '3.5'], dtype='<U32')

In [8]:
print(b)          # all are converted to string

['2' 'shreyas' '3.5']


In [9]:
l.pop()

678

In [10]:
l

[234, 345, 456, 567]

In [11]:
a.mean()

456.0

In [12]:
c = np.array([2, 3, 4, 5.5, True])

In [13]:
print(c)                  # True gets converted to 1.0

[2.  3.  4.  5.5 1. ]


---

In [14]:
# Slicing in Arrays

In [15]:
a[2:]

array([456, 567, 678])

In [16]:
a[-3:]

array([456, 567, 678])

In [17]:
b = a[3:]

In [18]:
b

array([567, 678])

In [19]:
b[:] = 111

In [20]:
b

array([111, 111])

In [21]:
a            # does not create a new array (unlike lists), b is only a view of a's slice, any changes to b will reflect in a

array([234, 345, 456, 111, 111])

In [26]:
c = a.copy()     # copy() can be used to make a copy where changes won't reflect in the original array

In [27]:
c

array([234, 345, 456, 111, 111])

In [28]:
c[0] = 0

In [29]:
c

array([  0, 345, 456, 111, 111])

In [30]:
a

array([234, 345, 456, 111, 111])